from aiogram import F, Router

from app.handlers.participant import (
    navigation,
    commands_ready,
    achievements_block4,
    task_block2,
    task_reply,
    project_event_photo_flow,
    projects_block5,
    event_activities_block15,
    event_activities_block7,
    event_plans_changed,
    surveys,
    about,
    directions_block7,
    cabinet,
    cabinet_hubs,
    departments,
    events_stability_block8,
    events,
    projects,
    questions,
    profile_settings,
    auction_block17,
    growth,
    partner_offers_block16,
    partners,
    point_transfer,
)

router = Router(name="participant")
router.message.filter(F.chat.type == "private")
router.callback_query.filter(F.message.chat.type == "private")
router.include_routers(
    navigation.router,
    commands_ready.router,
    achievements_block4.router,
    task_block2.router,
    task_reply.router,
    project_event_photo_flow.router,
    projects_block5.router,
    event_activities_block15.router,
    event_activities_block7.router,
    event_plans_changed.router,
    surveys.router,
    cabinet_hubs.router,
    directions_block7.router,
    cabinet.router,
    events_stability_block8.router,
    events.router,
    projects.router,
    departments.router,
    questions.router,
    about.router,
    profile_settings.router,
    auction_block17.router,
    growth.router,
    partner_offers_block16.router,
    partners.router,
    point_transfer.router,
)
