import {useState} from 'react';
import {fetchBookAnalytics,fetchWorkTasks,fetchWorkRoster,fetchWorkDecisions,fetchWorkAnnouncements,workWrite,describeActionError,type WorkTask} from '../../api/client';
import {useAsync} from '../../hooks/useAsync';
import {Card} from '../../components/Card';
import {AdminPulseScreen} from './AdminPulseScreen';
const labels:Record<string,string>={new:'Назначена',published:'Назначена',in_progress:'В работе',review:'На проверке',completed:'Выполнена',cancelled:'Отменена',overdue:'Просрочена'};
export function AdminWorkcenterScreen(){
 const [tab,setTab]=useState('tasks'),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('active');
 const [title,setTitle]=useState(''),[description,setDescription]=useState(''),[assignee,setAssignee]=useState(''),[deadline,setDeadline]=useState(''),[urgent,setUrgent]=useState(false);
 const [selected,setSelected]=useState<WorkTask|null>(null),[comment,setComment]=useState(''),[target,setTarget]=useState(''),[newDeadline,setNewDeadline]=useState('');
 const tasks=useAsync(fetchWorkTasks,[refresh]),roster=useAsync(fetchWorkRoster,[refresh]),decisions=useAsync(fetchWorkDecisions,[refresh]),announcements=useAsync(fetchWorkAnnouncements,[refresh]);
 async function run(f:()=>Promise<unknown>){setBusy(true);setError('');try{await f();setRefresh(x=>x+1);}catch(e){setError(describeActionError(e));}finally{setBusy(false);}}
 async function action(action:string,extra:Record<string,unknown>={}){if(!selected)return;await run(async()=>{const next=await workWrite(`tasks/${selected.id}/action`,{action,...extra});setSelected(next);});}
 const bookStats=useAsync(fetchBookAnalytics,[refresh]);
 const [notice,setNotice]=useState('');
 const people=roster.status==='ready'?roster.data:[];
 const all=tasks.status==='ready'?tasks.data:[];
 const list=all.filter(t=>filter==='all'||filter==='active'&&!['completed','cancelled'].includes(t.status)||filter==='free'&&t.assignee_id===null&&!['completed','cancelled'].includes(t.status)||filter==='blocker'&&!!t.blocker||filter==='overdue'&&!!t.deadline&&Date.parse(t.deadline)<Date.now()&&!['completed','cancelled'].includes(t.status)||t.status===filter);
 return <div style={{display:'grid',gap:16}}>
 <label>Раздел <select value={tab} onChange={e=>setTab(e.target.value)}>{[['tasks','Задачи'],['pulse','Пульс'],['decisions','Решения'],['announcements','Оповещения']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {tab==='pulse'&&<AdminPulseScreen/>}
 {tab==='tasks'&&<><Card><h2>Новая задача</h2><label>Название<input value={title} maxLength={255} onChange={e=>setTitle(e.target.value)}/></label><label>Описание<textarea value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Исполнитель<select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Свободная задача</option>{people.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>Срок (можно оставить пустым)<input type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label><input type="checkbox" checked={urgent} onChange={e=>setUrgent(e.target.checked)}/> Срочно</label><button disabled={busy||!title.trim()} onClick={()=>run(async()=>{await workWrite('tasks',{title,description,assignee_id:assignee?Number(assignee):null,deadline:deadline?new Date(deadline).toISOString():null,priority:urgent?'urgent':'normal'});setTitle('');setDescription('');})}>Создать и отправить в ЛИДЕРЫ</button></Card>
 <label>Показать<select value={filter} onChange={e=>setFilter(e.target.value)}>{[['active','Активные'],['all','Все'],['free','Свободные'],['review','На проверке'],['overdue','Просроченные'],['blocker','Блокеры'],['completed','Выполненные']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 {tasks.status==='error'&&<p>Не удалось загрузить задачи.</p>}{list.map(t=><Card key={t.id}><strong>#{t.id} {t.title}</strong><p>{t.assignee_name} · {t.blocker?'Есть проблема':t.assignee_id===null?'Свободна':labels[t.status]??t.status}</p><p>{t.deadline?new Date(t.deadline).toLocaleString('ru-RU'):'Без срока'}</p>{t.delivery_status!=='sent'&&<p>Карточка ожидает отправки в чат.</p>}<button onClick={()=>{setSelected(t);setTarget(t.assignee_id?String(t.assignee_id):'');setComment('');setNewDeadline('');}}>Открыть</button></Card>)}
 {selected&&<Card><h3>#{selected.id} {selected.title}</h3><p>{selected.description}</p>{selected.telegram_url&&<a href={selected.telegram_url} target="_blank" rel="noreferrer">Открыть карточку в ЛИДЕРАХ</a>}{selected.submissions.map(s=><p key={s.id}>{s.text||'Результат с вложением'}{s.has_file?' · Файл доступен через «Подробнее» в карточке Telegram':''}{s.comment?' · '+s.comment:''}</p>)}<label>Комментарий<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label>
 {selected.status==='review'&&<><button disabled={busy} onClick={()=>action('accept')}>Принять</button><button disabled={busy||!comment.trim()} onClick={()=>action('return',{comment})}>Вернуть на доработку</button></>}
 {!['completed','cancelled'].includes(selected.status)&&<><label>Исполнитель<select value={target} onChange={e=>setTarget(e.target.value)}><option value="">Свободна</option>{people.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><button disabled={busy} onClick={()=>action('assign',{assignee_id:target?Number(target):null})}>Передать</button><input aria-label="Новый срок" type="datetime-local" value={newDeadline} onChange={e=>setNewDeadline(e.target.value)}/><button disabled={busy} onClick={()=>action('deadline',{deadline:newDeadline?new Date(newDeadline).toISOString():null})}>{newDeadline?'Изменить срок':'Убрать срок'}</button><button disabled={busy} onClick={()=>action('urgent',{urgent:selected.priority!=='urgent'})}>{selected.priority==='urgent'?'Обычный приоритет':'Сделать срочной'}</button><button disabled={busy} onClick={()=>{if(window.confirm('Отменить задачу?'))void action('cancel');}}>Отменить задачу</button></>}
 <details><summary>История</summary>{selected.history.map((h,i)=><p key={i}>{new Date(h.at).toLocaleString('ru-RU')} · {h.action.split('.').pop()}</p>)}</details><button onClick={()=>setSelected(null)}>Закрыть</button></Card>}</>}
 {tab==='decisions'&&<>{decisions.status==='ready'&&decisions.data.map(d=><Card key={d.id}><p>{d.text}</p><p>{d.status==='resolved'?'Решено':d.status==='in_progress'?'В работе':d.status==='deferred'?'Отложено':'Ожидает решения'}</p><textarea aria-label="Решение" placeholder="Комментарий к решению" value={comment} onChange={e=>setComment(e.target.value)}/><select aria-label="Ответственный" value={target} onChange={e=>setTarget(e.target.value)}><option value="">Без ответственного</option>{people.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select>{[['in_progress','В работу'],['resolved','Решено'],['deferred','Отложить']].map(([v,l])=><button disabled={busy} key={v} onClick={()=>run(()=>workWrite(`decisions/${d.id}`,{status:v,comment,responsible_id:target?Number(target):null}))}>{l}</button>)}</Card>)}</>}
 {tab==='announcements'&&<><Card><h2>Публичные задания</h2><p>Создаёт 20 общих заданий один раз и отправляет одно понятное сообщение участникам и в общий чат.</p><button disabled={busy} onClick={()=>run(async()=>{const r=await workWrite('public-tasks/publish',{});setNotice(`Заданий: ${r.total}. Доставлено: ${r.sent}. Не доставлено: ${r.failed}. Оповещения: ${r.group_sent?'отправлено':'ожидает доставки'}.`);})}>Опубликовать 20 заданий и оповестить</button></Card><Card><h2>Книжный клуб</h2>{bookStats.status==='ready'&&<p>Подписчиков: {bookStats.data.subscribers} · Ответов: {bookStats.data.responses} · Ответили: {bookStats.data.respondents}. Личные тексты доступны только автору.</p>}<p>Запускает 48-дневный цикл авторских разборов и вопросов по книге.</p><button disabled={busy} onClick={()=>run(()=>workWrite('book-club/start',{}))}>Запустить 48 дней</button></Card><p>Старые объявления лидеров остаются в истории ниже.</p>{announcements.status==='ready'&&announcements.data.map(a=><Card key={a.id}><p>{a.text}</p><p>Ознакомились: {a.read} / {a.recipients}</p></Card>)}</>}
 </div>;
}
