export type VectorDimension = "energy" | "agency" | "autonomy" | "connection" | "direction";
export interface VectorQuestion { code: VectorDimension; title: string; text: string; }
export interface VectorOption { value: number; label: string; }
export interface VectorInsight { title?: string; insight?: string; why?: string; focus?: string; experiment?: string; semantic_tag?: string; methodology_version?: string; disclaimer?: string; }
export interface VectorCheckin { id:number; month:string; status:"in_progress"|"completed"; answers:Partial<Record<VectorDimension,number>>; state:Partial<Record<VectorDimension,number>>; index:number|null; delta:Partial<Record<VectorDimension,number>>; insight:VectorInsight; completed_at:string|null; context:{factors:string[];development_wants:string[]}; }
export interface VectorProfile { index:number|null; state:Partial<Record<VectorDimension,number>>; baseline:Partial<Record<VectorDimension,number>>; last_checkin_at:string|null; notice:string; }
export interface DevelopmentGoal { id:number; month:string; title:string; experiment:string|null; semantic_tag:string|null; status:string; is_custom:boolean; review:{result:string;obstacle:string|null;note:string|null}|null; }
export interface DevelopmentHome { title:string; subtitle:string; consent_required:boolean; consent_version:string; profile:VectorProfile|null; current_checkin:VectorCheckin|null; current_goal:DevelopmentGoal|null; questions:VectorQuestion[]; answer_options:VectorOption[]; context_options:string[]; development_wants:string[]; state_labels:Record<VectorDimension,string>; }
export interface AssessmentCard { code:string; title:string; description:string|null; source:string; methodology:string; license:string|null; license_status:string; estimated_minutes:number; min_age:number|null; recommended_retake_after_days:number|null; construct_type:string; available:boolean; what_it_shows?:string|null; important?:string; release_gate?:string|null; }
export interface DevelopmentPrivacy { consent_version:string; admin_visibility:{summary:boolean;interests:boolean;goals:boolean}; admin_can_see:string[]; private_only:string[]; }
